title: "Ludovica's Cybersecurity Blog"
description: "A personal blog for research projects and homework assignments in cybersecurity."
author: "Ludovica"
theme: minima
markdown: kramdown

# URL del sito
url: "https://ludovica01.github.io/statistics_2025-26/"

# Impostazioni sociali (facoltative)
github_username: ludovica01

# Abilita dark mode
minima:
  skin: dark
